### ISSUE TITLE
Need which type of value can request the link by old version value

### ISSUE THREAD

**Issue by saga0324** [TBT8A10/adups-fota#1]
I noticed that in your code we have to use the version string of the previous version of the current latest version in order to get the update, older ones don't get the intermediate update, is there a missing value?

**Comment by TBM13** [comment]
That's right. For some reason the server says we are up-to-date if we send it an old version string. I don't know if this is normal behaviour or not, I should install an old build on my tablet and try to search for updates there using the original ADUPS OTA app

**Comment by TBM13** [comment]
This no longer seems to be the case. Right now I'm getting the latest update using older version strings too, so maybe it was a server issue / bad configuration

**Comment by saga0324** [comment]
> This no longer seems to be the case. Right now I'm getting the latest update using older version strings too, so maybe it was a server issue / bad configuration

Seems like it decide by OEM, your tablet's OEM seems like build a diff package for every version to newest version
